/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author prathiksha
 */
public class med2 extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst=null;

    /**
     * Creates new form med2
     */
    public med2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        what = new javax.swing.JLabel();
        cust = new javax.swing.JButton();
        stock = new javax.swing.JButton();
        expire = new javax.swing.JButton();
        emp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 500));
        jPanel1.setLayout(null);

        what.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        what.setText("What would you like to select?");
        jPanel1.add(what);
        what.setBounds(470, 10, 470, 50);

        cust.setBackground(new java.awt.Color(36, 37, 42));
        cust.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        cust.setForeground(new java.awt.Color(255, 255, 255));
        cust.setText("CUSTOMER DETAILS");
        cust.setToolTipText("");
        cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custActionPerformed(evt);
            }
        });
        jPanel1.add(cust);
        cust.setBounds(80, 120, 200, 50);

        stock.setBackground(new java.awt.Color(36, 37, 42));
        stock.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        stock.setForeground(new java.awt.Color(255, 255, 255));
        stock.setText("STOCK");
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        jPanel1.add(stock);
        stock.setBounds(80, 400, 200, 50);

        expire.setBackground(new java.awt.Color(36, 37, 42));
        expire.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        expire.setForeground(new java.awt.Color(255, 0, 0));
        expire.setText("STOCK ABOUT TO EXPIRE");
        expire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expireActionPerformed(evt);
            }
        });
        jPanel1.add(expire);
        expire.setBounds(1100, 140, 200, 50);

        emp.setBackground(new java.awt.Color(36, 37, 42));
        emp.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        emp.setForeground(new java.awt.Color(255, 255, 255));
        emp.setText("EMPLOYEE DETAILS");
        emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empActionPerformed(evt);
            }
        });
        jPanel1.add(emp);
        emp.setBounds(1100, 400, 200, 50);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<< BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1150, 20, 150, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heartplus.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 10, 1366, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        med3 m3=new med3();
        m3.setVisible(true);
    }//GEN-LAST:event_custActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        med4 m4= new med4();
        m4.setVisible(true);
    }//GEN-LAST:event_stockActionPerformed

    private void expireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expireActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        med5 m5=new med5();
        m5.setVisible(true);
    }//GEN-LAST:event_expireActionPerformed

    private void empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        med6 m6=new med6();
        m6.setVisible(true);
    }//GEN-LAST:event_empActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        med1 m1=new med1();
        m1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(med2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(med2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(med2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(med2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new med2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton cust;
    private javax.swing.JButton emp;
    private javax.swing.JButton expire;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stock;
    private javax.swing.JLabel what;
    // End of variables declaration//GEN-END:variables
}
